export enum Topic {
  AI = 10,
  Angular = 20,
  BigData = 30,
  Blockchain = 40,
  C = 50,
  Cpp = 60,
  CSharp = 70,
  Cybersecurity = 80,
  DataScience = 90,
  DevOps = 100,
  DotNet = 110,
  Flutter = 120,
  Go = 130,
  IoT = 140,
  Java = 150,
  JavaScript = 160,
  Kotlin = 170,
  MachineLearning = 180,
  MobileDevelopment = 190,
  Python = 200,
  React = 210,
  Robotics = 220,
  Ruby = 230,
  Rust = 240,
  SoftwareArchitecture = 250,
  Swift = 260,
  Testing = 270,
  TypeScript = 280,
  WebDevelopment = 290,
}

export const TopicCustomMapping: { [key: number]: string } = {
  10: 'Artificial Intelligence',
  20: 'Angular Framework',
  30: 'Big Data Analytics',
  40: 'Blockchain Technology',
  50: 'C Programming',
  60: 'C++ Programming',
  70: 'C# Development',
  80: 'Cybersecurity Best Practices',
  90: 'Data Science Techniques',
  100: 'DevOps Tools',
  110: '.NET Framework',
  120: 'Flutter Mobile Development',
  130: 'Go Programming Language',
  140: 'Internet of Things (IoT)',
  150: 'Java Programming',
  160: 'JavaScript Ecosystem',
  170: 'Kotlin for Android',
  180: 'Machine Learning',
  190: 'Mobile App Development',
  200: 'Python for Data Science',
  210: 'React.js Frontend',
  220: 'Robotics Engineering',
  230: 'Ruby Programming',
  240: 'Rust Language',
  250: 'Software Architecture Patterns',
  260: 'Swift for iOS Development',
  270: 'Testing Methodologies',
  280: 'TypeScript Development',
  290: 'Web Development Trends',
};


export function getTopicName(value: number): string | undefined {
  return TopicCustomMapping[value];
}

